In [1]:
import pandas as pd

file_path = r'D:\Aa中工互联\工作安排\英格索兰\data\new历史数据.xlsx'
df = pd.read_excel(file_path)

# 获取瞬时流量

In [2]:
df.columns

Index(['timestamp', 'DLDZ_DQ200_SYSTEM_PI05.PV', 'DLDZ_AVS_SYSTEM_PI05.PV',
       'DLDZ_DQ200_LLJ01_FQ01.PV', 'DLDZ_AVS_LLJ01_FQ01.PV'],
      dtype='object')

In [3]:
df['时间'].head()

0   2025-05-01 00:00:00
1   2025-05-01 00:00:05
2   2025-05-01 00:00:10
3   2025-05-01 00:00:15
4   2025-05-01 00:00:20
Name: 时间, dtype: datetime64[ns]

In [3]:
df = df.sort_values(by='timestamp')

In [4]:
# 对 'DQ200累积流量' 和 'AVS累积流量' 分别做一阶差分
df['DQ200差分值'] = df['DLDZ_DQ200_LLJ01_FQ01.PV'].diff()
df['AVS差分值'] = df['DLDZ_AVS_LLJ01_FQ01.PV'].diff()

In [6]:
df.head()

,时间,DQ200系统压力,AVS系统压力,DQ200累积流量,AVS累积流量,DQ200差分值,AVS差分值
0,2025-05-01 00:00:00,6.071,6.402,329084448.0,54116824,NaN,NaN
1,2025-05-01 00:00:05,6.070,6.400,329084448.0,54116832,0.0,8.0
2,2025-05-01 00:00:10,6.062,6.407,329084480.0,54116844,32.0,12.0
3,2025-05-01 00:00:15,6.061,6.406,329084480.0,54116844,0.0,0.0
4,2025-05-01 00:00:20,6.066,6.396,329084480.0,54116856,0.0,12.0

In [5]:
# 删除第一个NaN行（如果需要）
df.dropna(inplace=True)
df.head()

,timestamp,DLDZ_DQ200_SYSTEM_PI05.PV,DLDZ_AVS_SYSTEM_PI05.PV,DLDZ_DQ200_LLJ01_FQ01.PV,DLDZ_AVS_LLJ01_FQ01.PV,DQ200差分值,AVS差分值
1,2025-05-01 00:01:00,6.14,6.37,329084512,54116908,64.0,84.0
2,2025-05-01 00:02:00,6.23,6.53,329084544,54116984,32.0,76.0
3,2025-05-01 00:03:00,6.30,6.79,329084608,54117072,64.0,88.0
4,2025-05-01 00:04:00,6.28,6.70,329084640,54117156,32.0,84.0
5,2025-05-01 00:05:00,6.23,6.62,329084704,54117232,64.0,76.0

In [6]:
df['瞬时流量'] = df['DQ200差分值'] + df['AVS差分值']

In [7]:
df.head()

,timestamp,DLDZ_DQ200_SYSTEM_PI05.PV,DLDZ_AVS_SYSTEM_PI05.PV,DLDZ_DQ200_LLJ01_FQ01.PV,DLDZ_AVS_LLJ01_FQ01.PV,DQ200差分值,AVS差分值,瞬时流量
1,2025-05-01 00:01:00,6.14,6.37,329084512,54116908,64.0,84.0,148.0
2,2025-05-01 00:02:00,6.23,6.53,329084544,54116984,32.0,76.0,108.0
3,2025-05-01 00:03:00,6.30,6.79,329084608,54117072,64.0,88.0,152.0
4,2025-05-01 00:04:00,6.28,6.70,329084640,54117156,32.0,84.0,116.0
5,2025-05-01 00:05:00,6.23,6.62,329084704,54117232,64.0,76.0,140.0

In [ ]:
df.to_excel('0瞬时流量.xlsx', index=False)